import type { MockIngredient } from "@/lib/mock-market-data";

/** Postgres-backed dinner ingredient catalog used for weekly-ad and provider matching. */
export const INTERNAL_CATALOG_INGREDIENTS: MockIngredient[] = [
  { id: "chicken-thighs", name: "Chicken thighs", category: "protein" },
  { id: "baby-potatoes", name: "Baby potatoes", category: "produce" },
  { id: "broccoli", name: "Broccoli", category: "produce" },
  { id: "lemon", name: "Lemon", category: "produce" },
  { id: "olive-oil", name: "Olive oil", category: "pantry" },
  { id: "black-beans", name: "Black beans", category: "pantry" },
  { id: "corn-tortillas", name: "Corn tortillas", category: "pantry" },
  { id: "cabbage", name: "Green cabbage", category: "produce" },
  { id: "lime", name: "Lime", category: "produce" },
  { id: "spaghetti", name: "Spaghetti", category: "pantry" },
  { id: "spinach", name: "Spinach", category: "produce" },
  { id: "parmesan", name: "Parmesan", category: "dairy" },
  { id: "butter", name: "Butter", category: "dairy" },
  { id: "tofu", name: "Extra-firm tofu", category: "protein" },
  { id: "jasmine-rice", name: "Jasmine rice", category: "pantry" },
  { id: "bell-peppers", name: "Bell peppers", category: "produce" },
  { id: "soy-sauce", name: "Soy sauce", category: "pantry" },
  { id: "green-onion", name: "Green onion", category: "produce" },
  { id: "ground-beef", name: "Ground beef", category: "protein" },
  { id: "chicken-breast", name: "Chicken breast", category: "protein" },
  { id: "ground-turkey", name: "Ground turkey", category: "protein" },
  { id: "yellow-onion", name: "Yellow onion", category: "produce" },
  { id: "garlic", name: "Garlic", category: "pantry" },
  { id: "carrots", name: "Carrots", category: "produce" },
  { id: "green-beans", name: "Green beans", category: "produce" },
  { id: "eggs", name: "Eggs", category: "dairy" },
  { id: "cheddar-cheese", name: "Cheddar cheese", category: "dairy" },
  { id: "whole-milk", name: "Whole milk", category: "dairy" },
  { id: "pasta-sauce", name: "Pasta sauce", category: "pantry" },
  { id: "canned-tomatoes", name: "Canned tomatoes", category: "pantry" },
  { id: "chicken-broth", name: "Chicken broth", category: "pantry" },
  { id: "pinto-beans", name: "Pinto beans", category: "pantry" },
  { id: "chickpeas", name: "Chickpeas", category: "pantry" },
  { id: "flour-tortillas", name: "Flour tortillas", category: "pantry" },
  { id: "penne-pasta", name: "Penne pasta", category: "pantry" },
  { id: "roma-tomatoes", name: "Roma tomatoes", category: "produce" },
  { id: "zucchini", name: "Zucchini", category: "produce" },
  { id: "mushrooms", name: "Mushrooms", category: "produce" },
  { id: "italian-sausage", name: "Italian sausage", category: "protein" },
  { id: "sour-cream", name: "Sour cream", category: "dairy" },
  { id: "mozzarella", name: "Mozzarella", category: "dairy" },
];

export const INTERNAL_CATALOG_INGREDIENT_IDS = INTERNAL_CATALOG_INGREDIENTS.map(
  (ingredient) => ingredient.id,
);
