import type { CatalogIngredient } from "@/lib/ingredient-category";

export type { IngredientCategory, CatalogIngredient } from "@/lib/ingredient-category";

/** Postgres-backed dinner ingredient catalog used for weekly-ad and provider matching. */
export const INTERNAL_CATALOG_INGREDIENTS: CatalogIngredient[] = [
  { id: "chicken-thighs", name: "Chicken thighs", category: "protein" },
  { id: "baby-potatoes", name: "Baby potatoes", category: "produce" },
  { id: "broccoli", name: "Broccoli", category: "produce" },
  { id: "lemon", name: "Lemon", category: "produce" },
  { id: "olive-oil", name: "Olive oil", category: "pantry" },
  { id: "black-beans", name: "Black beans", category: "pantry" },
  { id: "corn-tortillas", name: "Corn tortillas", category: "pantry" },
  { id: "cabbage", name: "Green cabbage", category: "produce" },
  { id: "lime", name: "Lime", category: "produce" },
  { id: "spaghetti", name: "Spaghetti", category: "pantry" },
  { id: "spinach", name: "Spinach", category: "produce" },
  { id: "parmesan", name: "Parmesan", category: "dairy" },
  { id: "butter", name: "Butter", category: "dairy" },
  { id: "tofu", name: "Extra-firm tofu", category: "protein" },
  { id: "jasmine-rice", name: "Jasmine rice", category: "pantry" },
  { id: "bell-peppers", name: "Bell peppers", category: "produce" },
  { id: "soy-sauce", name: "Soy sauce", category: "pantry" },
  { id: "green-onion", name: "Green onion", category: "produce" },
  { id: "ground-beef", name: "Ground beef", category: "protein" },
  { id: "chicken-breast", name: "Chicken breast", category: "protein" },
  { id: "ground-turkey", name: "Ground turkey", category: "protein" },
  { id: "yellow-onion", name: "Yellow onion", category: "produce" },
  { id: "garlic", name: "Garlic", category: "pantry" },
  { id: "carrots", name: "Carrots", category: "produce" },
  { id: "green-beans", name: "Green beans", category: "produce" },
  { id: "eggs", name: "Eggs", category: "dairy" },
  { id: "cheddar-cheese", name: "Cheddar cheese", category: "dairy" },
  { id: "whole-milk", name: "Whole milk", category: "dairy" },
  { id: "pasta-sauce", name: "Pasta sauce", category: "pantry" },
  { id: "canned-tomatoes", name: "Canned tomatoes", category: "pantry" },
  { id: "chicken-broth", name: "Chicken broth", category: "pantry" },
  { id: "pinto-beans", name: "Pinto beans", category: "pantry" },
  { id: "chickpeas", name: "Chickpeas", category: "pantry" },
  { id: "flour-tortillas", name: "Flour tortillas", category: "pantry" },
  { id: "penne-pasta", name: "Penne pasta", category: "pantry" },
  { id: "roma-tomatoes", name: "Roma tomatoes", category: "produce" },
  { id: "zucchini", name: "Zucchini", category: "produce" },
  { id: "mushrooms", name: "Mushrooms", category: "produce" },
  { id: "italian-sausage", name: "Italian sausage", category: "protein" },
  { id: "sour-cream", name: "Sour cream", category: "dairy" },
  { id: "mozzarella", name: "Mozzarella", category: "dairy" },
  { id: "cumin", name: "Ground cumin", category: "seasoning" },
  { id: "chili-powder", name: "Chili powder", category: "seasoning" },
  { id: "paprika", name: "Paprika", category: "seasoning" },
  { id: "black-pepper", name: "Black pepper", category: "seasoning" },
  { id: "salt", name: "Salt", category: "seasoning" },
  { id: "tomato-paste", name: "Tomato paste", category: "pantry" },
  { id: "vegetable-oil", name: "Vegetable oil", category: "pantry" },
  { id: "hot-sauce", name: "Hot sauce", category: "seasoning" },
  { id: "russet-potatoes", name: "Russet potatoes", category: "produce" },
  { id: "yukon-potatoes", name: "Yukon gold potatoes", category: "produce" },
  { id: "white-rice", name: "Long-grain white rice", category: "pantry" },
  { id: "brown-rice", name: "Brown rice", category: "pantry" },
  { id: "egg-noodles", name: "Egg noodles", category: "pantry" },
  { id: "fettuccine", name: "Fettuccine", category: "pantry" },
  { id: "elbow-macaroni", name: "Elbow macaroni", category: "pantry" },
  { id: "rice-noodles", name: "Rice noodles", category: "pantry" },
  { id: "garlic-powder", name: "Garlic powder", category: "seasoning" },
  { id: "onion-powder", name: "Onion powder", category: "seasoning" },
  { id: "dried-oregano", name: "Dried oregano", category: "seasoning" },
  { id: "dried-basil", name: "Dried basil", category: "seasoning" },
  { id: "cayenne", name: "Cayenne pepper", category: "seasoning" },
  { id: "italian-seasoning", name: "Italian seasoning", category: "seasoning" },
  { id: "taco-seasoning", name: "Taco seasoning mix", category: "seasoning" },
  { id: "rice-vinegar", name: "Rice vinegar", category: "seasoning" },
  { id: "balsamic-vinegar", name: "Balsamic vinegar", category: "seasoning" },
  { id: "dijon-mustard", name: "Dijon mustard", category: "seasoning" },
  { id: "all-purpose-flour", name: "All-purpose flour", category: "baking" },
  { id: "granulated-sugar", name: "Granulated sugar", category: "baking" },
  { id: "brown-sugar", name: "Brown sugar", category: "baking" },
  { id: "honey", name: "Honey", category: "baking" },
  { id: "baking-powder", name: "Baking powder", category: "baking" },
  { id: "baking-soda", name: "Baking soda", category: "baking" },
  { id: "vanilla-extract", name: "Vanilla extract", category: "baking" },
  { id: "cornstarch", name: "Cornstarch", category: "baking" },
  { id: "frozen-broccoli", name: "Frozen broccoli", category: "frozen" },
  { id: "frozen-green-beans", name: "Frozen green beans", category: "frozen" },
  { id: "frozen-corn", name: "Frozen corn", category: "frozen" },
  { id: "frozen-peas", name: "Frozen peas", category: "frozen" },
  { id: "frozen-spinach", name: "Frozen spinach", category: "frozen" },
  { id: "frozen-mixed-vegetables", name: "Frozen mixed vegetables", category: "frozen" },
  { id: "frozen-berries", name: "Frozen berries", category: "frozen" },
  { id: "bacon", name: "Bacon", category: "protein" },
  { id: "pork-shoulder", name: "Pork shoulder", category: "protein" },
  { id: "salmon-fillet", name: "Salmon fillet", category: "protein" },
  { id: "shrimp", name: "Shrimp", category: "protein" },
  { id: "celery", name: "Celery", category: "produce" },
  { id: "sweet-potato", name: "Sweet potato", category: "produce" },
  { id: "cilantro", name: "Cilantro", category: "produce" },
  { id: "jalapeno", name: "Jalapeño", category: "produce" },
  { id: "avocado", name: "Avocado", category: "produce" },
  { id: "cream-cheese", name: "Cream cheese", category: "dairy" },
  { id: "heavy-cream", name: "Heavy cream", category: "dairy" },
  { id: "plain-yogurt", name: "Plain yogurt", category: "dairy" },
  { id: "shredded-cheese-blend", name: "Shredded Mexican cheese blend", category: "dairy" },
  { id: "bread-loaf", name: "Sandwich bread", category: "pantry" },
  { id: "canned-corn", name: "Canned corn", category: "pantry" },
];

export const INTERNAL_CATALOG_INGREDIENT_IDS = INTERNAL_CATALOG_INGREDIENTS.map(
  (ingredient) => ingredient.id,
);
