-- Kroger provider search terms for remaining tracked ingredients (013).
-- Idempotent: safe to re-run on volumes that already applied 011.

insert into provider_search_terms (ingredient_id, provider, search_term, priority, notes)
values
  ('all-purpose-flour', 'kroger', 'all-purpose flour', 1, null),
  ('avocado', 'kroger', 'avocado', 1, null),
  ('bacon', 'kroger', 'bacon', 1, null),
  ('baking-powder', 'kroger', 'baking powder', 1, null),
  ('baking-soda', 'kroger', 'baking soda', 1, null),
  ('balsamic-vinegar', 'kroger', 'balsamic vinegar', 1, null),
  ('bell-peppers', 'kroger', 'bell peppers', 1, null),
  ('black-beans', 'kroger', 'black beans', 1, null),
  ('black-pepper', 'kroger', 'black pepper', 1, null),
  ('brown-rice', 'kroger', 'brown rice', 1, null),
  ('brown-sugar', 'kroger', 'brown sugar', 1, null),
  ('butter', 'kroger', 'butter', 1, null),
  ('canned-corn', 'kroger', 'sweet corn canned', 1, null),
  ('canned-tomatoes', 'kroger', 'canned tomatoes', 1, null),
  ('carrots', 'kroger', 'carrots', 1, null),
  ('cayenne', 'kroger', 'cayenne pepper', 1, null),
  ('celery', 'kroger', 'celery', 1, null),
  ('cheddar-cheese', 'kroger', 'cheddar cheese', 1, null),
  ('chicken-breast', 'kroger', 'chicken breast', 1, null),
  ('chicken-broth', 'kroger', 'chicken broth', 1, null),
  ('chicken-broth', 'kroger', 'chicken stock', 2, null),
  ('chickpeas', 'kroger', 'chickpeas', 1, null),
  ('chili-powder', 'kroger', 'chili powder', 1, null),
  ('cilantro', 'kroger', 'cilantro', 1, null),
  ('cornstarch', 'kroger', 'cornstarch', 1, null),
  ('corn-tortillas', 'kroger', 'corn tortillas', 1, null),
  ('cream-cheese', 'kroger', 'cream cheese', 1, null),
  ('dijon-mustard', 'kroger', 'dijon mustard', 1, null),
  ('dried-basil', 'kroger', 'dried basil', 1, null),
  ('dried-oregano', 'kroger', 'dried oregano', 1, null),
  ('egg-noodles', 'kroger', 'egg noodles', 1, null),
  ('eggs', 'kroger', 'eggs', 1, null),
  ('elbow-macaroni', 'kroger', 'elbow macaroni', 1, null),
  ('tofu', 'kroger', 'firm tofu', 1, null),
  ('fettuccine', 'kroger', 'fettuccine', 1, null),
  ('flour-tortillas', 'kroger', 'flour tortillas', 1, null),
  ('frozen-berries', 'kroger', 'frozen mixed berries', 1, null),
  ('frozen-broccoli', 'kroger', 'frozen broccoli florets', 1, null),
  ('frozen-broccoli', 'kroger', 'frozen broccoli', 2, null),
  ('frozen-corn', 'kroger', 'frozen sweet corn', 1, null),
  ('frozen-green-beans', 'kroger', 'frozen green beans', 1, null),
  ('frozen-mixed-vegetables', 'kroger', 'frozen mixed vegetables', 1, null),
  ('frozen-mixed-vegetables', 'kroger', 'frozen stir fry vegetables', 2, null),
  ('frozen-peas', 'kroger', 'frozen green peas', 1, null),
  ('frozen-spinach', 'kroger', 'frozen chopped spinach', 1, null),
  ('garlic', 'kroger', 'garlic', 1, null),
  ('garlic-powder', 'kroger', 'garlic powder', 1, null),
  ('granulated-sugar', 'kroger', 'granulated sugar', 1, null),
  ('green-beans', 'kroger', 'green beans', 1, null),
  ('cabbage', 'kroger', 'green cabbage', 1, null),
  ('green-onion', 'kroger', 'green onion', 1, null),
  ('ground-beef', 'kroger', 'ground beef', 1, null),
  ('cumin', 'kroger', 'ground cumin', 1, null),
  ('ground-turkey', 'kroger', 'ground turkey', 1, null),
  ('heavy-cream', 'kroger', 'heavy cream', 1, null),
  ('honey', 'kroger', 'honey', 1, null),
  ('hot-sauce', 'kroger', 'hot sauce', 1, null),
  ('italian-sausage', 'kroger', 'italian sausage', 1, null),
  ('italian-seasoning', 'kroger', 'italian seasoning', 1, null),
  ('jalapeno', 'kroger', 'jalapeño', 1, null),
  ('jasmine-rice', 'kroger', 'jasmine rice', 1, null),
  ('lime', 'kroger', 'lime', 1, null),
  ('white-rice', 'kroger', 'long grain white rice', 1, null),
  ('mozzarella', 'kroger', 'mozzarella', 1, null),
  ('mushrooms', 'kroger', 'mushrooms', 1, null),
  ('onion-powder', 'kroger', 'onion powder', 1, null),
  ('paprika', 'kroger', 'paprika', 1, null),
  ('parmesan', 'kroger', 'parmesan', 1, null),
  ('pasta-sauce', 'kroger', 'marinara sauce', 1, null),
  ('penne-pasta', 'kroger', 'penne pasta', 1, null),
  ('pinto-beans', 'kroger', 'pinto beans', 1, null),
  ('plain-yogurt', 'kroger', 'plain yogurt', 1, null),
  ('pork-shoulder', 'kroger', 'pork shoulder', 1, null),
  ('rice-noodles', 'kroger', 'rice noodles', 1, null),
  ('rice-vinegar', 'kroger', 'rice vinegar', 1, null),
  ('roma-tomatoes', 'kroger', 'roma tomatoes', 1, null),
  ('russet-potatoes', 'kroger', 'russet potatoes', 1, null),
  ('salmon-fillet', 'kroger', 'salmon fillet', 1, null),
  ('salt', 'kroger', 'salt', 1, null),
  ('bread-loaf', 'kroger', 'white sandwich bread', 1, null),
  ('shredded-cheese-blend', 'kroger', 'Mexican cheese blend', 1, null),
  ('shrimp', 'kroger', 'shrimp', 1, null),
  ('sour-cream', 'kroger', 'sour cream', 1, null),
  ('soy-sauce', 'kroger', 'soy sauce', 1, null),
  ('spaghetti', 'kroger', 'spaghetti', 1, null),
  ('spinach', 'kroger', 'spinach', 1, null),
  ('sweet-potato', 'kroger', 'sweet potato', 1, null),
  ('taco-seasoning', 'kroger', 'taco seasoning mix', 1, null),
  ('tomato-paste', 'kroger', 'tomato paste', 1, null),
  ('vanilla-extract', 'kroger', 'vanilla extract', 1, null),
  ('vegetable-oil', 'kroger', 'vegetable oil', 1, null),
  ('whole-milk', 'kroger', 'whole milk', 1, null),
  ('yellow-onion', 'kroger', 'yellow onion', 1, null),
  ('yukon-potatoes', 'kroger', 'yukon gold potatoes', 1, null),
  ('zucchini', 'kroger', 'zucchini', 1, null)
on conflict (provider, ingredient_id, search_term) do nothing;
