#!/usr/bin/env bash
# Ingest container entrypoint.
#
# Modes (env):
#   YUM4LESS_INGEST_ONCE=1     — run scheduled ingest once, exit with its code (dry-run / first proof)
#   YUM4LESS_INGEST_CRON=0     — skip cron; sleep forever so host/TrueNAS can `docker exec` instead
#   (default)                  — start cron in foreground; daily job at 0 3 * * * (see crontab)
#
# Cron does not inherit Docker `environment:` — we dump a sourced env file for the job.
set -euo pipefail

cd /app

mkdir -p /var/log/yum4less /etc/yum4less
touch /var/log/yum4less/ingest.log

# Persist container env for /etc/cron.d jobs (cron starts with a minimal environment).
# Skip noisy / non-exportable keys.
{
  echo "# Generated by /entrypoint.sh — do not edit"
  printenv | sort | while IFS= read -r line; do
    key="${line%%=*}"
    case "$key" in
      ""|_|HOME|HOSTNAME|PWD|SHLVL|TERM|OLDPWD|LS_COLORS) continue ;;
    esac
    # shell-escape value for `export KEY='...'`
    value="${line#*=}"
    value_escaped=$(printf '%s' "$value" | sed "s/'/'\\\\''/g")
    printf "export %s='%s'\n" "$key" "$value_escaped"
  done
} > /etc/yum4less/ingest.env
chmod 600 /etc/yum4less/ingest.env

if [[ "${YUM4LESS_INGEST_ONCE:-0}" == "1" ]]; then
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] YUM4LESS_INGEST_ONCE=1 — running scheduled ingest once."
  exec npm run ingest:weekly-ads:scheduled
fi

cron_enabled="${YUM4LESS_INGEST_CRON:-1}"
if [[ "${cron_enabled}" == "0" || "${cron_enabled}" == "false" || "${cron_enabled}" == "no" ]]; then
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] In-container cron disabled (YUM4LESS_INGEST_CRON=0)."
  echo "Trigger manually: docker exec yum4less-ingest npm run ingest:weekly-ads:scheduled"
  echo "Or: docker exec yum4less-ingest npm run check:ranked-price-freshness"
  exec tail -F /var/log/yum4less/ingest.log
fi

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] Starting cron (daily ingest at 03:00 container local time; set TZ)."
# -f = foreground (required for Docker PID 1)
exec cron -f
