import type { CatalogIngredient } from "@/lib/ingredient-category";

/** Weekly-ad product titles rarely mirror catalog names; use short grocery aliases. */
const WEEKLY_AD_INGREDIENT_SEARCH_ALIASES: Record<string, string[]> = {
  "chicken-thighs": [
    "chicken thighs",
    "chicken thigh",
    "boneless chicken thighs",
    "family pack chicken thighs",
  ],
  "chicken-breast": [
    "chicken breast",
    "chicken breasts",
    "boneless chicken breast",
    "boneless skinless chicken breast",
    "skinless chicken breast",
  ],
  "ground-beef": [
    "ground beef",
    "lean ground beef",
    "fresh ground beef",
    "hamburger meat",
    "ground chuck",
  ],
  "ground-turkey": [
    "ground turkey",
    "lean ground turkey",
    "fresh ground turkey",
    "turkey breast ground",
  ],
  "baby-potatoes": ["baby potatoes", "mini potatoes", "creamer potatoes", "red potatoes"],
  broccoli: ["broccoli", "broccoli florets", "broccoli crowns"],
  lemon: ["lemon", "lemons", "fresh lemons"],
  "olive-oil": ["olive oil", "extra virgin olive oil"],
  "black-beans": ["black beans", "canned black beans"],
  "corn-tortillas": ["corn tortillas", "tortillas"],
  cabbage: ["green cabbage", "cabbage", "cabbage head"],
  lime: ["lime", "limes", "fresh limes"],
  spaghetti: ["spaghetti", "pasta spaghetti", "spaghetti pasta"],
  spinach: ["spinach", "baby spinach", "fresh spinach"],
  parmesan: ["parmesan", "parmesan cheese", "shredded parmesan", "parmesan wedge"],
  butter: ["butter", "salted butter", "unsalted butter"],
  tofu: ["extra-firm tofu", "firm tofu", "tofu"],
  "jasmine-rice": ["jasmine rice", "white rice", "long grain rice"],
  "bell-peppers": [
    "bell peppers",
    "bell pepper",
    "red bell pepper",
    "green bell pepper",
    "peppers",
  ],
  "soy-sauce": ["soy sauce", "low sodium soy sauce"],
  "green-onion": ["green onion", "scallion", "scallions"],
  "yellow-onion": [
    "yellow onion",
    "yellow onions",
    "sweet onion",
    "sweet onions",
    "onion",
    "onions",
  ],
  garlic: ["garlic", "fresh garlic", "garlic bulb"],
  carrots: ["carrots", "baby carrots", "carrot bag", "whole carrots"],
  "green-beans": [
    "green beans",
    "fresh green beans",
    "string beans",
    "snap beans",
    "french green beans",
  ],
  eggs: ["eggs", "large eggs", "grade a eggs", "dozen eggs", "cage free eggs"],
  "cheddar-cheese": [
    "cheddar cheese",
    "cheddar",
    "shredded cheddar",
    "sharp cheddar",
    "mild cheddar",
  ],
  "whole-milk": ["whole milk", "milk gallon", "vitamin d milk", "2% milk", "1% milk"],
  "pasta-sauce": [
    "pasta sauce",
    "spaghetti sauce",
    "marinara sauce",
    "tomato pasta sauce",
    "classico pasta sauce",
  ],
  "canned-tomatoes": [
    "canned tomatoes",
    "diced tomatoes",
    "crushed tomatoes",
    "stewed tomatoes",
    "petite diced tomatoes",
    "chopped tomatoes",
  ],
  "chicken-broth": [
    "chicken broth",
    "chicken stock",
    "low sodium chicken broth",
    "organic chicken broth",
    "reduced sodium chicken broth",
  ],
  "pinto-beans": [
    "pinto beans",
    "canned pinto beans",
    "refried pinto beans",
    "pinto bean",
  ],
  chickpeas: [
    "chickpeas",
    "garbanzo beans",
    "canned chickpeas",
    "garbanzo bean",
  ],
  "flour-tortillas": [
    "flour tortillas",
    "soft flour tortillas",
    "burrito tortillas",
    "large flour tortillas",
    "tortilla wraps",
  ],
  "penne-pasta": [
    "penne pasta",
    "penne",
    "penne rigate",
    "rigatoni",
    "short pasta",
  ],
  "roma-tomatoes": [
    "roma tomatoes",
    "roma tomato",
    "vine ripe tomatoes",
    "fresh tomatoes",
    "on the vine tomatoes",
    "grape tomatoes",
  ],
  zucchini: [
    "zucchini",
    "green zucchini",
    "summer squash",
    "medium zucchini",
  ],
  mushrooms: [
    "mushrooms",
    "white mushrooms",
    "baby bella mushrooms",
    "cremini mushrooms",
    "button mushrooms",
    "sliced mushrooms",
  ],
  "italian-sausage": [
    "italian sausage",
    "mild italian sausage",
    "hot italian sausage",
    "sweet italian sausage",
    "italian pork sausage",
  ],
  "sour-cream": [
    "sour cream",
    "light sour cream",
    "reduced fat sour cream",
    "dairy sour cream",
  ],
  mozzarella: [
    "mozzarella",
    "mozzarella cheese",
    "shredded mozzarella",
    "part skim mozzarella",
    "fresh mozzarella",
  ],
  cumin: ["ground cumin", "cumin", "cumin spice"],
  "chili-powder": ["chili powder", "chile powder", "mild chili powder"],
  paprika: ["paprika", "smoked paprika", "sweet paprika"],
  "black-pepper": ["black pepper", "ground black pepper", "peppercorn"],
  salt: ["salt", "iodized salt", "table salt", "sea salt"],
  "tomato-paste": ["tomato paste", "tomato paste can"],
  "vegetable-oil": ["vegetable oil", "canola oil", "cooking oil"],
  "hot-sauce": ["hot sauce", "crystal hot sauce", "louisiana hot sauce"],
  "russet-potatoes": ["russet potatoes", "russet potato", "baking potatoes", "idaho potatoes"],
  "yukon-potatoes": ["yukon gold potatoes", "yukon potatoes", "gold potatoes"],
  "white-rice": ["white rice", "long grain rice", "long grain white rice", "enriched rice"],
  "brown-rice": ["brown rice", "whole grain brown rice"],
  "egg-noodles": ["egg noodles", "wide egg noodles", "medium egg noodles"],
  fettuccine: ["fettuccine", "fettuccine pasta", "fettuccini"],
  "elbow-macaroni": ["elbow macaroni", "elbow pasta", "macaroni"],
  "rice-noodles": ["rice noodles", "rice stick noodles", "pad thai noodles"],
  "garlic-powder": ["garlic powder", "granulated garlic"],
  "onion-powder": ["onion powder", "granulated onion"],
  "dried-oregano": ["dried oregano", "oregano leaves"],
  "dried-basil": ["dried basil", "basil leaves"],
  cayenne: ["cayenne pepper", "cayenne", "ground cayenne"],
  "italian-seasoning": ["italian seasoning", "italian herbs"],
  "taco-seasoning": ["taco seasoning", "taco seasoning mix", "mccormick taco seasoning"],
  "rice-vinegar": ["rice vinegar", "seasoned rice vinegar"],
  "balsamic-vinegar": ["balsamic vinegar", "balsamic vinaigrette"],
  "dijon-mustard": ["dijon mustard", "grey poupon"],
  "all-purpose-flour": ["all purpose flour", "all-purpose flour", "ap flour"],
  "granulated-sugar": ["granulated sugar", "white sugar", "pure cane sugar"],
  "brown-sugar": ["brown sugar", "light brown sugar", "dark brown sugar"],
  honey: ["honey", "clover honey", "raw honey"],
  "baking-powder": ["baking powder", "double acting baking powder"],
  "baking-soda": ["baking soda", "sodium bicarbonate"],
  "vanilla-extract": ["vanilla extract", "pure vanilla", "vanilla"],
  cornstarch: ["cornstarch", "corn starch"],
  "frozen-broccoli": ["frozen broccoli", "steamable broccoli", "broccoli florets frozen"],
  "frozen-green-beans": ["frozen green beans", "frozen cut green beans"],
  "frozen-corn": ["frozen corn", "frozen sweet corn", "steamable corn"],
  "frozen-peas": ["frozen peas", "sweet peas frozen"],
  "frozen-spinach": ["frozen spinach", "chopped spinach frozen"],
  "frozen-mixed-vegetables": ["frozen mixed vegetables", "frozen stir fry vegetables", "California blend"],
  "frozen-berries": ["frozen berries", "mixed berries frozen", "frozen strawberries"],
  bacon: ["bacon", "thick cut bacon", "center cut bacon", "bacon strips"],
  "pork-shoulder": ["pork shoulder", "pork butt", "boston butt"],
  "salmon-fillet": ["salmon fillet", "salmon fillets", "fresh salmon", "atlantic salmon"],
  shrimp: ["shrimp", "raw shrimp", "peeled shrimp", "tail off shrimp"],
  celery: ["celery", "celery hearts", "celery stalks"],
  "sweet-potato": ["sweet potato", "sweet potatoes", "yams"],
  cilantro: ["cilantro", "fresh cilantro", "coriander leaves"],
  jalapeno: ["jalapeno", "jalapeño", "jalapeno pepper"],
  avocado: ["avocado", "hass avocado", "avocados"],
  "cream-cheese": ["cream cheese", "philadelphia cream cheese", "soft cream cheese"],
  "heavy-cream": ["heavy cream", "heavy whipping cream", "whipping cream"],
  "plain-yogurt": ["plain yogurt", "greek yogurt plain", "whole milk yogurt"],
  "shredded-cheese-blend": [
    "mexican cheese blend",
    "shredded mexican cheese",
    "fiesta blend cheese",
    "four cheese mexican",
  ],
  "bread-loaf": ["sandwich bread", "white bread", "wheat bread loaf", "bread loaf"],
  "canned-corn": ["canned corn", "whole kernel corn", "sweet corn canned"],
};

export function getWeeklyAdIngredientSearchTerms(ingredient: CatalogIngredient): string[] {
  const aliases = WEEKLY_AD_INGREDIENT_SEARCH_ALIASES[ingredient.id] ?? [];
  const terms = [ingredient.name, ...aliases];
  return [...new Set(terms.map((term) => term.trim()).filter(Boolean))];
}
