import type { MockIngredient } from "@/lib/mock-market-data";

/** Weekly-ad product titles rarely mirror catalog names; use short grocery aliases. */
const WEEKLY_AD_INGREDIENT_SEARCH_ALIASES: Record<string, string[]> = {
  "chicken-thighs": [
    "chicken thighs",
    "chicken thigh",
    "boneless chicken thighs",
    "family pack chicken thighs",
  ],
  "chicken-breast": [
    "chicken breast",
    "chicken breasts",
    "boneless chicken breast",
    "boneless skinless chicken breast",
    "skinless chicken breast",
  ],
  "ground-beef": [
    "ground beef",
    "lean ground beef",
    "fresh ground beef",
    "hamburger meat",
    "ground chuck",
  ],
  "ground-turkey": [
    "ground turkey",
    "lean ground turkey",
    "fresh ground turkey",
    "turkey breast ground",
  ],
  "baby-potatoes": ["baby potatoes", "yukon gold potatoes", "red potatoes", "potatoes"],
  broccoli: ["broccoli", "broccoli florets", "broccoli crowns"],
  lemon: ["lemon", "lemons", "fresh lemons"],
  "olive-oil": ["olive oil", "extra virgin olive oil"],
  "black-beans": ["black beans", "canned black beans"],
  "corn-tortillas": ["corn tortillas", "tortillas"],
  cabbage: ["green cabbage", "cabbage", "cabbage head"],
  lime: ["lime", "limes", "fresh limes"],
  spaghetti: ["spaghetti", "pasta spaghetti", "spaghetti pasta"],
  spinach: ["spinach", "baby spinach", "fresh spinach"],
  parmesan: ["parmesan", "parmesan cheese", "shredded parmesan", "parmesan wedge"],
  butter: ["butter", "salted butter", "unsalted butter"],
  tofu: ["extra-firm tofu", "firm tofu", "tofu"],
  "jasmine-rice": ["jasmine rice", "white rice", "long grain rice"],
  "bell-peppers": [
    "bell peppers",
    "bell pepper",
    "red bell pepper",
    "green bell pepper",
    "peppers",
  ],
  "soy-sauce": ["soy sauce", "low sodium soy sauce"],
  "green-onion": ["green onion", "scallion", "scallions"],
  "yellow-onion": [
    "yellow onion",
    "yellow onions",
    "sweet onion",
    "sweet onions",
    "onion",
    "onions",
  ],
  garlic: ["garlic", "fresh garlic", "garlic bulb"],
  carrots: ["carrots", "baby carrots", "carrot bag", "whole carrots"],
  "green-beans": [
    "green beans",
    "fresh green beans",
    "string beans",
    "snap beans",
    "french green beans",
  ],
  eggs: ["eggs", "large eggs", "grade a eggs", "dozen eggs", "cage free eggs"],
  "cheddar-cheese": [
    "cheddar cheese",
    "cheddar",
    "shredded cheddar",
    "sharp cheddar",
    "mild cheddar",
  ],
  "whole-milk": ["whole milk", "milk gallon", "vitamin d milk", "2% milk", "1% milk"],
  "pasta-sauce": [
    "pasta sauce",
    "spaghetti sauce",
    "marinara sauce",
    "tomato pasta sauce",
    "classico pasta sauce",
  ],
  "canned-tomatoes": [
    "canned tomatoes",
    "diced tomatoes",
    "crushed tomatoes",
    "stewed tomatoes",
    "petite diced tomatoes",
    "chopped tomatoes",
  ],
  "chicken-broth": [
    "chicken broth",
    "chicken stock",
    "low sodium chicken broth",
    "organic chicken broth",
    "reduced sodium chicken broth",
  ],
  "pinto-beans": [
    "pinto beans",
    "canned pinto beans",
    "refried pinto beans",
    "pinto bean",
  ],
  chickpeas: [
    "chickpeas",
    "garbanzo beans",
    "canned chickpeas",
    "garbanzo bean",
  ],
  "flour-tortillas": [
    "flour tortillas",
    "soft flour tortillas",
    "burrito tortillas",
    "large flour tortillas",
    "tortilla wraps",
  ],
  "penne-pasta": [
    "penne pasta",
    "penne",
    "penne rigate",
    "rigatoni",
    "short pasta",
  ],
  "roma-tomatoes": [
    "roma tomatoes",
    "roma tomato",
    "vine ripe tomatoes",
    "fresh tomatoes",
    "on the vine tomatoes",
    "grape tomatoes",
  ],
  zucchini: [
    "zucchini",
    "green zucchini",
    "summer squash",
    "medium zucchini",
  ],
  mushrooms: [
    "mushrooms",
    "white mushrooms",
    "baby bella mushrooms",
    "cremini mushrooms",
    "button mushrooms",
    "sliced mushrooms",
  ],
  "italian-sausage": [
    "italian sausage",
    "mild italian sausage",
    "hot italian sausage",
    "sweet italian sausage",
    "italian pork sausage",
  ],
  "sour-cream": [
    "sour cream",
    "light sour cream",
    "reduced fat sour cream",
    "dairy sour cream",
  ],
  mozzarella: [
    "mozzarella",
    "mozzarella cheese",
    "shredded mozzarella",
    "part skim mozzarella",
    "fresh mozzarella",
  ],
};

export function getWeeklyAdIngredientSearchTerms(ingredient: MockIngredient): string[] {
  const aliases = WEEKLY_AD_INGREDIENT_SEARCH_ALIASES[ingredient.id] ?? [];
  const terms = [ingredient.name, ...aliases];
  return [...new Set(terms.map((term) => term.trim()).filter(Boolean))];
}
