const WEEKLY_AD_MATCH_REJECT_PATTERNS: Record<string, RegExp[]> = {
  "baby-potatoes": [/chips/i, /crisps/i, /snack/i],
  butter: [/peanut butter/i, /almond butter/i, /cashew butter/i],
  broccoli: [/broccoli cheese soup/i, /frozen broccoli/i, /steamable/i],
  lemon: [/lemonade/i],
  lime: [/limeade/i],
  spaghetti: [/noodle soup/i],
  "chicken-thighs": [/breast/i, /tenderloin/i, /wing/i, /drumstick/i],
  "chicken-breast": [/thigh/i, /drumstick/i, /wing/i],
  "ground-beef": [/broth/i, /stock/i, /jerky/i, /corned beef/i, /beef patty/i],
  "ground-turkey": [/broth/i, /stock/i, /jerky/i, /turkey bacon/i, /turkey breast whole/i],
  eggs: [/egg nog/i, /egg noodle/i, /easter/i, /chocolate/i, /substitute/i],
  "yellow-onion": [
    /onion ring/i,
    /onion powder/i,
    /french onion/i,
    /green onion/i,
    /scallion/i,
  ],
  garlic: [/garlic bread/i, /garlic powder/i, /garlic salt/i],
  "canned-tomatoes": [/tomato paste/i, /ketchup/i, /pizza sauce/i, /pasta sauce/i, /marinara/i],
  carrots: [/carrot cake/i, /baby food/i, /juice/i],
  "cheddar-cheese": [/mac and cheese/i, /cracker/i, /spread/i],
  "whole-milk": [
    /almond milk/i,
    /oat milk/i,
    /coconut milk/i,
    /soy milk/i,
    /chocolate milk/i,
    /evaporated/i,
    /condensed/i,
  ],
  "green-beans": [/coffee/i, /jelly/i, /bean bag chair/i],
  "pasta-sauce": [/pizza sauce/i],
  "chicken-broth": [/gravy/i, /beef broth/i, /beef stock/i, /vegetable broth/i],
  "pinto-beans": [/refried beans/i, /bean dip/i],
  chickpeas: [/hummus/i, /falafel/i],
  "flour-tortillas": [/tortilla chips/i, /tostada/i, /hard shell/i],
  "penne-pasta": [/mac and cheese/i, /noodle soup/i, /spaghetti/i],
  "roma-tomatoes": [
    /tomato paste/i,
    /ketchup/i,
    /pizza sauce/i,
    /pasta sauce/i,
    /marinara/i,
    /diced tomatoes/i,
    /crushed tomatoes/i,
    /sun-dried/i,
  ],
  zucchini: [/zucchini bread/i, /zucchini noodles/i],
  mushrooms: [/mushroom soup/i, /mushroom gravy/i, /stuffed mushroom/i],
  "italian-sausage": [
    /breakfast sausage/i,
    /smoked sausage/i,
    /kielbasa/i,
    /bratwurst/i,
    /sausage patty/i,
  ],
  "sour-cream": [/onion dip/i, /potato chip/i, /sour cream and onion/i],
  mozzarella: [/string cheese/i, /cheese stick snack/i],
  cumin: [/cumin seed/i],
  "chili-powder": [/chili lime/i, /chili paste/i],
  paprika: [/paprika potato chips/i],
  "black-pepper": [/pepper jack/i, /bell pepper/i, /pepperoni/i],
  salt: [/salted caramel/i, /saltine/i, /epsom salt/i, /rock salt ice/i],
  "tomato-paste": [/pasta sauce/i, /marinara/i, /ketchup/i],
  "vegetable-oil": [/vegetable soup/i, /vegetable tray/i],
  "hot-sauce": [/buffalo wing sauce/i],
  "russet-potatoes": [/potato chips/i, /potato salad/i],
  "yukon-potatoes": [/potato chips/i, /mashed potato/i],
  "white-rice": [/rice krispies/i, /rice cake/i, /rice vinegar/i],
  "brown-rice": [/rice krispies/i, /rice cake/i],
  "egg-noodles": [/ramen/i],
  fettuccine: [/alfredo sauce/i],
  "elbow-macaroni": [/mac and cheese kit/i],
  "rice-noodles": [/rice paper/i],
  "garlic-powder": [/garlic bread/i, /garlic salt/i],
  "onion-powder": [/onion ring/i, /onion dip/i],
  "dried-oregano": [/oregano oil/i],
  "all-purpose-flour": [/flour tortillas/i, /self rising flour/i, /cake flour/i],
  honey: [/honey mustard/i, /honey bun/i, /honey ham/i, /honey nut/i],
  "brown-sugar": [/brown sugar cinnamon/i, /oatmeal/i],
  "granulated-sugar": [/sugar free/i, /powdered sugar/i],
  "vanilla-extract": [/vanilla yogurt/i, /vanilla ice cream/i],
  "frozen-broccoli": [/broccoli cheese soup/i],
  "frozen-green-beans": [/green bean casserole mix/i],
  "frozen-corn": [/corn dog/i, /popcorn/i],
  "frozen-spinach": [/spinach dip/i, /spinach artichoke/i],
  "frozen-berries": [/berry yogurt/i, /berry pie/i],
  bacon: [/bacon bits salad/i, /bacon ranch dressing/i],
  "salmon-fillet": [/salmon patty/i, /smoked salmon spread/i],
  shrimp: [/shrimp chips/i, /shrimp sauce/i],
  celery: [/celery salt/i, /celery seed/i],
  "sweet-potato": [/sweet potato pie/i, /sweet potato fries frozen appetizer/i],
  cilantro: [/cilantro lime dressing/i, /cilantro sauce/i],
  jalapeno: [/jalapeno chips/i, /pickled jalapeno/i],
  avocado: [/avocado oil/i, /guacamole/i],
  "cream-cheese": [/cream cheese spread flavored/i],
  "heavy-cream": [/ice cream/i, /coffee creamer/i],
  "plain-yogurt": [/yogurt drink/i, /yogurt tube kids/i],
  "shredded-cheese-blend": [/cheese dip/i, /queso/i],
  "bread-loaf": [/bread crumbs/i, /garlic bread/i, /stuffing mix/i],
  "canned-corn": [/corn chips/i, /cornbread mix/i],
};

export function shouldRejectWeeklyAdIngredientMatch(input: {
  ingredientId: string;
  productName: string;
}) {
  const patterns = WEEKLY_AD_MATCH_REJECT_PATTERNS[input.ingredientId] ?? [];
  return patterns.some((pattern) => pattern.test(input.productName));
}
