/** Non-food flyer lines. Avoid bare tokens that hit dinners: garden, grill, paper. */
const JUNK_PATTERNS: RegExp[] = [
  /\bchips?\b/i,
  /\bcrisps?\b/i,
  /\bcandy\b/i,
  /\bcookie/i,
  /\bcake\b/i,
  /\bcakes\b/i,
  /\bpop-?tarts?\b/i,
  /\bjerky\b/i,
  /\bbeer\b/i,
  /\bwine\b/i,
  /\blager\b/i,
  /\bale\b/i,
  /\bsoda\b/i,
  /\bcola\b/i,
  /\bjuice\b/i,
  /\bslider bags?\b/i,
  /\bfreezer bags?\b/i,
  /\bgarbage bags?\b/i,
  /\bstorage bags?\b/i,
  /\bgadget/i,
  /\bfootball\b/i,
  /\bkalanchoe\b/i,
  /\bcoir\b/i,
  /\bdoor mat\b/i,
  /\bfrying pan\b/i,
  /\bbaking pan\b/i,
  /\bsheet pan\b/i,
  /\bdress\b/i,
  /\bshirt\b/i,
  /\bshoe/i,
  /\bheadphone/i,
  /\bearpods?\b/i,
  /\bpillow\b/i,
  /\brug\b/i,
  /\bentr[eé]es?\b/i,
  /\bheat.?and.?eat\b/i,
  /\bcupcakes?\b/i,
  /\bdiaper/i,
  /\bdetergent\b/i,
  /\bshampoo\b/i,
  /\bpaper towels?\b/i,
  /\blaptops?\b/i,
  /\bssd\b/i,
  /\brtx\b/i,
  /\busb\b/i,
  /\bkeyboards?\b/i,
  /\bgb ram\b/i,
  /\bpatio\b/i,
  /\bgazebos?\b/i,
  /\bsofas?\b/i,
  /\bcandles?\b/i,
  /\btowels?\b/i,
  /\bmops?\b/i,
  /\bpaper plates?\b/i,
  /\btoothbrushes?\b/i,
  /\btoothpaste\b/i,
  /\bbody wash\b/i,
  // Pet aisle — do not use bare pet/dog/cat (PET milk, hot dog, catfish).
  /\bdog foods?\b/i,
  /\bcat foods?\b/i,
  /\bpet foods?\b/i,
  /\bpet treats?\b/i,
  /\bdog treats?\b/i,
  /\bcat treats?\b/i,
  /\bpet toys?\b/i,
  /\bpet beds?\b/i,
  /\bpet supplies\b/i,
  /\bcat litter\b/i,
  /\bkitty litter\b/i,
  /\bpuppy foods?\b/i,
  /\bkitten foods?\b/i,
  /\bpuppy chow\b/i,
  /\bbird seeds?\b/i,
  /\bfish foods?\b/i,
  /\bflea (?:and|&) tick\b/i,
  /\btick (?:and|&) flea\b/i,
  /\brawhides?\b/i,
  /\bcatnip\b/i,
  /\bhamsters?\b/i,
  /\bguinea pigs?\b/i,
  /\bheart to tail\b/i,
  /\bsweatshirts?\b/i,
  /\bslippers?\b/i,
  /\bjoggers?\b/i,
  /\bkirkton house\b/i,
  /\bcrofton\b/i,
  /\bsilvercrest\b/i,
  /\bmainstays\b/i,
  /\bbetter homes(?:\s*&\s*|\s+)gardens\b/i,
  /\blicensed children/i,
  /\blicensed toddler/i,
  /\bcorona\b/i,
  /\bmodelo\b/i,
  /\bpacifico\b/i,
  /\bnobilo\b/i,
  /\btrivento\b/i,
  // Apparel / footwear — all chains; do not use bare "tee" (hits iced tea).
  /\bcrocs\b/i,
  /\bsandals?\b/i,
  /\bflip flops?\b/i,
  /\bsneakers?\b/i,
  /\bjeans?\b/i,
  /\bdenim\b/i,
  /\bpolos?\b/i,
  /\bsweaters?\b/i,
  /\btank tops?\b/i,
  /\bgraphic tee\b/i,
  /\bshorts\b/i,
  /\bskirtalls?\b/i,
  /\bbackpacks?\b/i,
  /\bdaypacks?\b/i,
  // Electronics / cameras
  /\bearbuds?\b/i,
  /\bwireless earbuds?\b/i,
  /\bdesktops?\b/i,
  /\bwindows 11\b/i,
  /\binstax\b/i,
  /\binstant camera\b/i,
  // Cleaning / laundry / personal care
  /\bsunscreen\b/i,
  /\bspf\s*\d/i,
  /\bdisinfectant\b/i,
  /\blysol\b/i,
  /\bfabric rinse\b/i,
  /\bscent booster\b/i,
  /\bin-wash\b/i,
  // Makeup / skincare — do not use bare cream or oil (sour cream, olive oil).
  /\bmakeup\b/i,
  /\bcosmetics?\b/i,
  /\bskincare\b/i,
  /\bskin care\b/i,
  /\bmascaras?\b/i,
  /\blipsticks?\b/i,
  /\blip gloss\b/i,
  /\blip balms?\b/i,
  /\bconcealers?\b/i,
  /\beyeliners?\b/i,
  /\bmoisturizers?\b/i,
  /\blotions?\b/i,
  /\bserums?\b/i,
  /\bestee lauder\b/i,
  /\bperfumes?\b/i,
  /\bcolognes?\b/i,
  /\bfragrances?\b/i,
  /\bnail polish\b/i,
  /\bface wash\b/i,
  /\beye creams?\b/i,
  /\bnight creams?\b/i,
  /\bhand creams?\b/i,
  /\bface creams?\b/i,
  /\banti-?aging\b/i,
  /\bretinol\b/i,
  // Small appliances / housewares that are not dinner foods
  /\bwaffle makers?\b/i,
  /\belectric griddles?\b/i,
  /\bdinner plates?\b/i,
  /\bfood storage containers?\b/i,
  /\bbento box\b/i,
  /\btoilet papers?\b/i,
  /\btoilet tissues?\b/i,
  /\bblenders?\b/i,
  /\bslow cookers?\b/i,
  /\bdisinfecting\b/i,
  /\bmulti-surface cleaner\b/i,
  /\bgaming mouse\b/i,
  /\blunch box\b/i,
  /\bvacuums?\b/i,
  /\bmini fridge\b/i,
  /\binkjet\b/i,
  /\bprinters?\b/i,
  /\bbox fans?\b/i,
  /\btumblers?\b/i,
  /\binsect trap\b/i,
  /\bmattress(?:es)?\b/i,
  /\btoasters?\b/i,
  /\btoaster ovens?\b/i,
  /\bcountertop ovens?\b/i,
  /\bair fryers?\b/i,
  /\bair fry function\b/i,
  /\bdishwasher safe\b/i,
  /\bdishwashers?\b/i,
  /\bfrench door\b/i,
  /\bpressure cookers?\b/i,
  /\brice cookers?\b/i,
  /\bcoffee makers?\b/i,
  /\belectric skillets?\b/i,
  /\bfood processors?\b/i,
  /\bice makers?\b/i,
  /\bicemakers?\b/i,
  /\bmulti-cookers?\b/i,
  /\binstant pots?\b/i,
  /\bdining chairs?\b/i,
  /\bdining tables?\b/i,
  /\boutdoor dining\b/i,
  /\bdumbbells?\b/i,
  /\bkettlebells?\b/i,
  /\bbarbells?\b/i,
  /\bweight sets?\b/i,
  /\bdyson\b/i,
  /\bairwraps?\b/i,
  /\bstraighteners?\b/i,
  /\bgaming monitors?\b/i,
  /\bsmart tvs?\b/i,
  /\bqled\b/i,
  /\bcar seats?\b/i,
  /\bbluetooth speakers?\b/i,
  /\bbluetooth\b/i,
  /\bportable speakers?\b/i,
  /\bhand mixers?\b/i,
  /\bwomen's and women's\b/i,
  /\bwomen's plus\b/i,
  /\btrack pants?\b/i,
  /\bfleece pants?\b/i,
  /\bfleece short\b/i,
  /\bskorts?\b/i,
  /\bhigh rise pant\b/i,
  /\bmini tee\b/i,
  /\bnetgear\b/i,
  /\bwifi 6\b/i,
  /\bwater filtration\b/i,
  /\bfaucet mount\b/i,
  /\bmopping cloths?\b/i,
  /\bair fresheners?\b/i,
  /\bglade\b/i,
  /\bmold and mildew\b/i,
  /\bstain eraser\b/i,
  /\bpizza rolls?\b/i,
  /\bfrito lay\b/i,
  /\btortes?\b/i,
  /\bdonettes?\b/i,
  /\bsnack packs?\b/i,
  /\bcereal cups?\b/i,
  /\bjonny pops\b/i,
  /\bkool-?aid\b/i,
  /\bcountry time\b/i,
  /\bbrownies?\b/i,
  /\bkeurig\b/i,
  /\bgreen mountain\b/i,
  /\bstouffer/i,
  /\bhealthy choice\b/i,
  /\bmarie callender\b/i,
  /\bjimmy dean\b/i,
  /\bhostess\b/i,
  /\blittle debbie\b/i,
  /\bfly traps?\b/i,
  /\bfruit flies\b/i,
  /\brefurbished\b/i,
  /\bjeggings?\b/i,
  /\bjersey tee\b/i,
  // Walmart GM leftover: furniture, baby gear, coolers, drinkware, cleaners.
  // Do not use bare chair/table/grill/cooler/coffee/monitor/baby (dinners + baby spinach).
  /\bbaby monitors?\b/i,
  /\bvideo monitors?\b/i,
  /\bplayards?\b/i,
  /\bplaypens?\b/i,
  /\bpack n play\b/i,
  /\bpack 'n play\b/i,
  /\blayettes?\b/i,
  /\bnursery centers?\b/i,
  /\bcamping chairs?\b/i,
  /\bchaise lounges?\b/i,
  /\bcoffee tables?\b/i,
  /\bend tables?\b/i,
  /\btub chairs?\b/i,
  /\boffice chairs?\b/i,
  /\bbean bag chairs?\b/i,
  /\bsaucer chairs?\b/i,
  /\boutdoor seating\b/i,
  /\bupholstered\b/i,
  /\bbookcases?\b/i,
  /\bfabric dressers?\b/i,
  /\bchest of drawers?\b/i,
  /\bvanity desks?\b/i,
  /\btoy organizers?\b/i,
  /\bcornhole\b/i,
  /\bbean bag toss\b/i,
  /\bladder toss\b/i,
  /\bminnark\b/i,
  /\bice chests?\b/i,
  /\bsoft coolers?\b/i,
  /\bcharcoal (?:grills?|briquettes)\b/i,
  /\bgriddle kits?\b/i,
  /\bgrills? with wheels\b/i,
  /\bloafers?\b/i,
  /\bballet flats?\b/i,
  /\bcami tops?\b/i,
  /\bwater bottles?\b/i,
  /\bsandwich bags?\b/i,
  /\bcross body\b/i,
  /\bwindex\b/i,
  /\bfabuloso\b/i,
  /\bcomet\b/i,
  /\bfloor cleaners?\b/i,
  /\ball.?purpose cleaners?\b/i,
  /\bcleaning powders?\b/i,
  /\bstella artois\b/i,
  /\bmichelob\b/i,
  /\byuengling\b/i,
  /\btwisted tea\b/i,
  /\bbusch\b/i,
  /\bnatural light\b/i,
  /\bkeystone\b/i,
  /\bblue moon\b/i,
  // Owner-queue leftovers (2026-09-09): pharmacy, seltzer/soda, paper, flowers,
  // cereal/snack drinks. Do not use bare tea/pad/water/pizza/daisy/rose-as-prefix
  // (iced tea, dinner kit, watermelon, pizza dough, Daisy sour cream, rosemary).
  /\bdeodorants?\b/i,
  /\bantiperspirants?\b/i,
  /\bmouthwash\b/i,
  /\boral rinse\b/i,
  /\btampons?\b/i,
  /\bpanty liners?\b/i,
  /\bincontinence\b/i,
  /\balways discreet\b/i,
  /\bkotex\b/i,
  /\btampax\b/i,
  /\bpoise pads?\b/i,
  /\bdepend underwear\b/i,
  /\badvil\b/i,
  /\btylenol\b/i,
  /\baleve\b/i,
  /\bzyrtec\b/i,
  /\bclaritin\b/i,
  /\bflonase\b/i,
  /\bmucinex\b/i,
  /\btheraflu\b/i,
  /\brobitussin\b/i,
  /\bnexium\b/i,
  /\btums\b/i,
  /\bpepcid\b/i,
  /\bimodium\b/i,
  /\bbenadryl\b/i,
  /\bmotrin\b/i,
  /\bexcedrin\b/i,
  /\bvoltaren\b/i,
  /\bneosporin\b/i,
  /\bband-aid\b/i,
  /\bpain reliever\b/i,
  /\ballergy relief\b/i,
  /\ballergy medicine\b/i,
  /\bgillette\b/i,
  /\bvenus cartridge\b/i,
  /\bdisposable razors?\b/i,
  /\bhand soaps?\b/i,
  /\bbar soaps?\b/i,
  /\bfabric softeners?\b/i,
  /\bbath tissues?\b/i,
  /\bbathroom tissues?\b/i,
  /\bfacial tissues?\b/i,
  /\bkleenex\b/i,
  /\benergizer\b/i,
  /\balkaline (?:long-lasting )?batter(?:y|ies)\b/i,
  /\binsect repellent\b/i,
  /\bant & roach\b/i,
  /\broach killing\b/i,
  /\bhaircolou?r\b/i,
  /\broot touch-up\b/i,
  /\binfant formula\b/i,
  /\bbaby wipes\b/i,
  /\bdietary supplements?\b/i,
  /\bhard seltzers?\b/i,
  /\bhard iced tea\b/i,
  /\bspiked lemonade\b/i,
  /\bwhite claw\b/i,
  /\btruly hard seltzer\b/i,
  /\bhigh noon\b/i,
  /\bsmirnoff\b/i,
  /\bheineken\b/i,
  /\bmiller lite\b/i,
  /\bmiller high life\b/i,
  /\bcoors\b/i,
  /\bpabst\b/i,
  /\bsamuel adams\b/i,
  /\bsam adams\b/i,
  /\bsierra nevada\b/i,
  /\bnew belgium\b/i,
  /\bnütrl\b/i,
  /\bnutrl\b/i,
  /\bcayman jack\b/i,
  /\bjack daniel/i,
  /\byes way ros/i,
  /\bapothic\b/i,
  /\bbota box\b/i,
  /\bmalbec\b/i,
  /\bprosecco\b/i,
  /\bbold rock\b/i,
  /\bpepsi\b/i,
  /\b7-?up\b/i,
  /\bmountain dew\b/i,
  /\bgatorade\b/i,
  /\bred bull\b/i,
  /\bmonster energy\b/i,
  /\benergy drinks?\b/i,
  /\bpurified water\b/i,
  /\bsparkling water\b/i,
  /\bspring water\b/i,
  /\bartesian water\b/i,
  /\balkaline water\b/i,
  /\bdasani\b/i,
  /\bessentia\b/i,
  /\bkombucha\b/i,
  /\bk-cups?\b/i,
  /\bcoffee pods?\b/i,
  /\biced coffee\b/i,
  /\bcereals?\b/i,
  /\bgranola bars?\b/i,
  /\bprotein bars?\b/i,
  /\bprotein shakes?\b/i,
  /\blunchables\b/i,
  /\bpopcorn\b/i,
  /\bchex mix\b/i,
  /\bpringles\b/i,
  /\btostitos\b/i,
  /\bgoldfish\b/i,
  /\bbouquets?\b/i,
  /\bdozen roses?\b/i,
  /\bbloom haus\b/i,
  /\bfoliage plants?\b/i,
  /\bvase ready\b/i,
  /\borchids?\b/i,
  /\bpom daisy\b/i,
  /\bpullovers?\b/i,
  /\bheavyweight tees\b/i,
  /\bsocks\b/i,
  /\bclogs?\b/i,
  /\bcoverups?\b/i,
  /\bcookware sets?\b/i,
  /\bpots and pans\b/i,
  /\bdeep fryers?\b/i,
  /\bupright freezer\b/i,
  /\babove ground\b/i,
  /\bsplash pads?\b/i,
  /\bbasketball hoops?\b/i,
  /\bswing sets?\b/i,
  /\binflatable\b/i,
  /\bnespresso\b/i,
  /\bpanini press\b/i,
  /\bcrock-?pots?\b/i,
  /\bmeal prep containers?\b/i,
  /\bplastic hangers?\b/i,
  /\blight bulbs?\b/i,
  /\bsunglasses\b/i,
  /\bmulti-purpose lighters?\b/i,
  /\bglass cleaner\b/i,
  /\bbathroom cleaner\b/i,
  /\bcarpet cleaner\b/i,
  /\bgrout cleaner\b/i,
  /\bsweeping cloths?\b/i,
  /\bscrub daddy\b/i,
  /\bsponges\b/i,
  /\bfor dogs\b/i,
  /\bfor cats\b/i,
  /\bdog chews?\b/i,
  /\bdog snacks?\b/i,
  /\bhot wheels\b/i,
  /\bcharcoal\b/i,
  /\btotino\b/i,
  /\bdigiorno\b/i,
  /\bhot pockets\b/i,
  /\bkingsford\b/i,
  // Live leftover queue (2026-09-10): Aldi Halloween/GM, leftover drinks/snacks,
  // pharmacy, toys. Do not use bare pizza, tea, pad, paper, or each-as-substring
  // (pizza dough, iced tea, peaches).
  /\bthe halloween collection\b/i,
  /\bhalloween\b/i,
  /\bplush\b/i,
  /\bgarlands?\b/i,
  /\bwreaths?\b/i,
  /\bdehydrators?\b/i,
  /\bparchment paper\b/i,
  /\bgallon bags?\b/i,
  /\bpress & seal\b/i,
  /\bactivity sets?\b/i,
  /\bboard books?\b/i,
  /\bfinger puppets?\b/i,
  /\bball assortments?\b/i,
  /\bleggings?\b/i,
  /\brain jackets?\b/i,
  /\bstadium seats?\b/i,
  /\bumbrellas?\b/i,
  /\bfashion totes?\b/i,
  /\bpajamas?\b/i,
  /\bponchos?\b/i,
  /\bbow belts?\b/i,
  /\bbow flats?\b/i,
  /\blong-sleeve t-shirts?\b/i,
  /\bbarn jackets?\b/i,
  /\bstorage towers?\b/i,
  /\bblanket ladders?\b/i,
  /\bottoman\b/i,
  /\bbooster packs?\b/i,
  /\bpok[eé]mon\b/i,
  /\benergy bars?\b/i,
  /\bchocolate assortments?\b/i,
  /\btruffles?\b/i,
  /\bcroissants?\b/i,
  /\bbreakfast bowls?\b/i,
  /\bbreakfast sandwiches?\b/i,
  /\bfrench toast sticks\b/i,
  /\bpancake mix\b/i,
  /\bwaffle cones?\b/i,
  /\binstant oatmeal\b/i,
  /\btakeout box\b/i,
  /\bmeal kits?\b/i,
  /\bskillet dinner\b/i,
  /\bfrozen dinners?\b/i,
  /\bfrozen meals?\b/i,
  /\bmega bowls?\b/i,
  /\bmeal for one\b/i,
  /\bpizza singles\b/i,
  /\bseltzer\b/i,
  /\blemonades?\b/i,
  /\bpuraqua\b/i,
  /\bbodyarmor\b/i,
  /\balani\b/i,
  /\bcelsius\b/i,
  /\belectrolit\b/i,
  /\bangel soft\b/i,
  /\balways radiant\b/i,
  /\bflexfoam\b/i,
  /\btena\b/i,
  /\balka-seltzer\b/i,
  /\ballegra\b/i,
  /\bacetaminophen\b/i,
  /\bepsom salt\b/i,
  /\bmiralax\b/i,
  /\bicy hot\b/i,
  /\btiger balm\b/i,
  /\baspirin\b/i,
  /\bneutrogena\b/i,
  /\bcolgate\b/i,
  /\bwhitestrips\b/i,
  /\bhand sanitizer\b/i,
  /\bwindshield washer\b/i,
  /\bparty cups\b/i,
  /\bplates or bowls\b/i,
  /\bnapkins\b/i,
  /\btrash bags\b/i,
  /\birish spring\b/i,
  /\bstout\b/i,
  /\bhard lemonade\b/i,
  /\bstella rosa\b/i,
  /\bla marca\b/i,
  /\bmeiomi\b/i,
  /\bmionetto\b/i,
  /\bkim crawford\b/i,
  /\bkorbel\b/i,
  /\bfruit snacks?\b/i,
  /\bgummies\b/i,
  /\btaquitos\b/i,
  /\bcrackers\b/i,
  /\btraining pants\b/i,
  /\bbaby foods?\b/i,
  /\bgerber\b/i,
  /\bbeech-nut\b/i,
  /\bplaysets?\b/i,
  /\bbubble blower\b/i,
  /\bhopscotch\b/i,
  /\blounge float\b/i,
  /\btrainers\b/i,
  /\blace trim\b/i,
  /\bambiano\b/i,
  /\bsohl\b/i,
  /\bserra ladies\b/i,
  /\blive in style\b/i,
  /\bdisney\b/i,
  /\bliquid i\.?v\b/i,
  /\bstarbucks\b/i,
  /\bfood storage set\b/i,
  /\bmeal prep\b/i,
  /\bkind bars?\b/i,
  /\brxbars?\b/i,
  /\bclif\b/i,
  /\bl[aä]rabar\b/i,
  /\buncrustables\b/i,
  /\bpb&j\b/i,
  /\bcaulipower\b/i,
  /\bfreschetta\b/i,
  /\btombstone pizza\b/i,
  /\bred baron\b/i,
  /\bdanimals\b/i,
  /\bensure\b/i,
  /\bpowerade\b/i,
  /\bhawaiian punch\b/i,
  /\bsunny delight\b/i,
  /\bbig k\b/i,
  /\bgold peak\b/i,
  /\bglac[eé]au\b/i,
  /\bsmartwater\b/i,
  /\bvitaminwater\b/i,
  /\bmini roses?\b/i,
  /\bfall mums\b/i,
  /\bdip®?\s*tee\b/i,
  /\bgame day (?:top|pajamas)\b/i,
  /\bheathy choice\b/i,
  /\btall kitchen bags\b/i,
  /\bq mixers\b/i,
  /\bguinness\b/i,
  /\bfitflop\b/i,
  /\bintex\b/i,
  /\bplay day\b/i,
  /\blittle tikes\b/i,
  /\bbattat\b/i,
  /\bramen cups?\b/i,
  /\bnissin\b/i,
  /\bprotein pudding\b/i,
  /\bprotein snack\b/i,
  /\bgranola\b/i,
  /\bkefir\b/i,
  /\bfruit drink\b/i,
  /\bfountain drink\b/i,
  /\bprotein powder\b/i,
  /\bmelatonin\b/i,
  /\bground coffee\b/i,
  /\binstant coffee\b/i,
  /\bdunkin\b/i,
  /\btrail mix\b/i,
  /\btakis\b/i,
  /\bpillsbury\b/i,
  /\bjell-?o\b/i,
  /\bfood lion drinks\b/i,
  /\bhappy tot\b/i,
  /\bhappy baby\b/i,
  /\boutshine\b/i,
  /\bblue bunny\b/i,
  /\bbomb pop\b/i,
  /\bhi-c\b/i,
  /\bminute maid\b/i,
  /\bwater enhancer\b/i,
  /\bprotein meals?\b/i,
  /\bprotein bowls?\b/i,
  /\bryl tea\b/i,
];

export function isWeeklyAdJunkProduct(productName: string): boolean {
  const trimmed = productName.trim();
  if (trimmed.length < 2) {
    return true;
  }
  if (/^each$/i.test(trimmed)) {
    return true;
  }
  if (/^gain$/i.test(trimmed)) {
    return true;
  }
  return JUNK_PATTERNS.some((pattern) => pattern.test(trimmed));
}

/** True when the raw flyer title or the normalized label matches junk. */
export function flyerLineLooksLikeJunk(
  rawProductName: string,
  normalizedLabel?: string,
): boolean {
  if (isWeeklyAdJunkProduct(rawProductName)) {
    return true;
  }
  if (normalizedLabel && isWeeklyAdJunkProduct(normalizedLabel)) {
    return true;
  }
  return false;
}
