/** Non-food flyer lines. Avoid bare tokens that hit dinners: garden, grill, paper. */
const JUNK_PATTERNS: RegExp[] = [
  /\bchips?\b/i,
  /\bcrisps?\b/i,
  /\bcandy\b/i,
  /\bcookie/i,
  /\bcake\b/i,
  /\bpop-?tarts?\b/i,
  /\bjerky\b/i,
  /\bbeer\b/i,
  /\bwine\b/i,
  /\blager\b/i,
  /\bale\b/i,
  /\bsoda\b/i,
  /\bcola\b/i,
  /\bjuice\b/i,
  /\bslider bags?\b/i,
  /\bfreezer bags?\b/i,
  /\bgarbage bags?\b/i,
  /\bstorage bags?\b/i,
  /\bgadget/i,
  /\bfootball\b/i,
  /\bkalanchoe\b/i,
  /\bcoir\b/i,
  /\bdoor mat\b/i,
  /\bfrying pan\b/i,
  /\bbaking pan\b/i,
  /\bsheet pan\b/i,
  /\bdress\b/i,
  /\bshirt\b/i,
  /\bshoe/i,
  /\bheadphone/i,
  /\bearpods?\b/i,
  /\bpillow\b/i,
  /\brug\b/i,
  /\bentr[eé]e\b/i,
  /\bheat.?and.?eat\b/i,
  /\bcupcakes?\b/i,
  /\bdiaper/i,
  /\bdetergent\b/i,
  /\bshampoo\b/i,
  /\bpaper towels?\b/i,
  /\blaptops?\b/i,
  /\bssd\b/i,
  /\brtx\b/i,
  /\busb\b/i,
  /\bkeyboards?\b/i,
  /\bgb ram\b/i,
  /\bpatio\b/i,
  /\bgazebos?\b/i,
  /\bsofas?\b/i,
  /\bcandles?\b/i,
  /\btowels?\b/i,
  /\bmops?\b/i,
  /\bpaper plates?\b/i,
  /\btoothbrushes?\b/i,
  /\btoothpaste\b/i,
  /\bbody wash\b/i,
  /\bdog foods?\b/i,
  /\bcat foods?\b/i,
  /\bpet toys?\b/i,
  /\bsweatshirts?\b/i,
  /\bslippers?\b/i,
  /\bjoggers?\b/i,
  /\bkirkton house\b/i,
  /\bcrofton\b/i,
  /\bsilvercrest\b/i,
  /\bmainstays\b/i,
  /\bbetter homes(?:\s*&\s*|\s+)gardens\b/i,
  /\bheart to tail\b/i,
  /\blicensed children/i,
  /\blicensed toddler/i,
  /\bcorona\b/i,
  /\bmodelo\b/i,
  /\bpacifico\b/i,
  /\bnobilo\b/i,
  /\btrivento\b/i,
  // Apparel / footwear — all chains; do not use bare "tee" (hits iced tea).
  /\bcrocs\b/i,
  /\bsandals?\b/i,
  /\bflip flops?\b/i,
  /\bsneakers?\b/i,
  /\bjeans?\b/i,
  /\bdenim\b/i,
  /\bpolos?\b/i,
  /\bsweaters?\b/i,
  /\btank tops?\b/i,
  /\bgraphic tee\b/i,
  /\bshorts\b/i,
  /\bskirtalls?\b/i,
  /\bbackpacks?\b/i,
  /\bdaypacks?\b/i,
  // Electronics / cameras
  /\bearbuds?\b/i,
  /\bwireless earbuds?\b/i,
  /\bdesktops?\b/i,
  /\bwindows 11\b/i,
  /\binstax\b/i,
  /\binstant camera\b/i,
  // Cleaning / laundry / personal care
  /\bsunscreen\b/i,
  /\bspf\s*\d/i,
  /\bdisinfectant\b/i,
  /\blysol\b/i,
  /\bfabric rinse\b/i,
  /\bscent booster\b/i,
  /\bin-wash\b/i,
  // Small appliances / housewares that are not dinner foods
  /\bwaffle makers?\b/i,
  /\belectric griddles?\b/i,
  /\bdinner plates?\b/i,
  /\bfood storage containers?\b/i,
  /\bbento box\b/i,
  /\btoilet papers?\b/i,
  /\btoilet tissues?\b/i,
  /\bblenders?\b/i,
  /\bslow cookers?\b/i,
  /\bdisinfecting\b/i,
  /\bmulti-surface cleaner\b/i,
  /\bgaming mouse\b/i,
  /\blunch box\b/i,
  /\bvacuums?\b/i,
  /\bmini fridge\b/i,
  /\binkjet\b/i,
  /\bprinters?\b/i,
  /\bbox fans?\b/i,
  /\btumblers?\b/i,
  /\binsect trap\b/i,
  /\bmattress(?:es)?\b/i,
  /\btoasters?\b/i,
  /\bjeggings?\b/i,
  /\bjersey tee\b/i,
];

export function isWeeklyAdJunkProduct(productName: string): boolean {
  const trimmed = productName.trim();
  if (trimmed.length < 2) {
    return true;
  }
  return JUNK_PATTERNS.some((pattern) => pattern.test(trimmed));
}

/** True when the raw flyer title or the normalized label matches junk. */
export function flyerLineLooksLikeJunk(
  rawProductName: string,
  normalizedLabel?: string,
): boolean {
  if (isWeeklyAdJunkProduct(rawProductName)) {
    return true;
  }
  if (normalizedLabel && isWeeklyAdJunkProduct(normalizedLabel)) {
    return true;
  }
  return false;
}
